### ISSUE TITLE
Bugs when specifying a name

### ISSUE THREAD

**Issue by brettgoulder** [heroku/heroku-certs#4]
```
❯ heroku _certs
Name                    Endpoint                             Common Name(s)        Expires               Trusted  Type
──────────────────────  ───────────────────────────────────  ────────────────────  ────────────────────  ───────  ────────
procompsognathus-87601  us-east-1-a-sni.route.herokuapp.com  www.brettgoulder.com  2017-03-21 21:35 UTC  False    SNI
hyogo-67203             hyogo-67203.herokussl.com            www.brettgoulder.com  2017-03-21 21:35 UTC  False    Endpoint

~/code/bretts-test-app master*
❯ heroku _certs:remove hyogo-67203
 ▸    Error: Unexpected argument hyogo-67203
 ▸    Usage: heroku _certs:remove
 ▸    You gave this command too many arguments. Try the command again without these extra arguments.
 ▸
 ▸    See more information with heroku _certs:remove --help

~/code/bretts-test-app master*
❯ heroku _certs:remove
 ▸    Must pass --name when more than one endpoint
```

`heroku _certs:remove hyogo-67203` should work, right?

**Comment by ransombriggs** [comment]
@brettgoulder This is an oddity carried over from the certs command.  If you pass an arg there with the current certificate regardless of whether or not the name exists.  See my example with the old command where I ask it to delete `foobar.com` but instead of erroring it deletes gunma-54089 instead.  I admit this is weird and different than the rest of the toolbelt and I would like to fix it.  Just to be clear, I want to make it behave the following way.

heroku _certs:remove 
  * no args does a delete of the only cert if there is only one, otherwise errors
  * currently implemented
  * I do not love this, but kept it around for backwards compatibility
heroku _certs:remove --name <name>
  * delete by name if one matches, name should be distinct
  * currently implemented
heroku _certs:remove --endpoint <name>
  * delete by endpoint if one matches, if multiple errors out and suggests --name instead
  * currently implemented
heroku _certs:remove <name>
  * equivalent to heroku _certs:remove --name <name>
  * will be added
```
-> % heroku certs --app thawing-temple-8799
Endpoint                   Common Name(s)               Expires               Trusted
-------------------------  ---------------------------  --------------------  -------
gunma-54089.herokussl.com  ssl.heroku-cli-sni-test.com  2016-05-05 14:57 UTC  False
rbriggs@ebriggs-ltm [12:59:29] [~/src/github.com/heroku/heroku-cli] [dev]
-> % heroku certs:remove foobar.com --app thawing-temple-8799

 !    WARNING: Potentially Destructive Action
 !    This command will remove the endpoint gunma-54089.herokussl.com from thawing-temple-8799.
 !    To proceed, type "thawing-temple-8799" or re-run this command with --confirm thawing-temple-8799

> thawing-temple-8799
Removing SSL Endpoint gunma-54089.herokussl.com from thawing-temple-8799... done
NOTE: Billing is still active. Remove SSL Endpoint add-on to stop billing.
rbriggs@ebriggs-ltm [12:59:50]
```

**Comment by ransombriggs** [comment]
@dickeyxxx I was going to do this yesterday so following commands would look like this, but ran into a hiccup.
```
  _certs:info [NAME]             #  show certificate information for an SSL certificate
  _certs:remove [NAME]           #  remove an SSL certificate from an app
  _certs:rollback [NAME]         #  rollback an SSL certificate from an app
```
For update I would really like it to be NAME first then CRT & KEY, but that would break backwards compatibility horribly.  How ugly do you think it would be to have NAME last ?
```
  _certs:update CRT KEY [NAME]   #  update an SSL certificate on an app
```

**Comment by dickeyxxx** [comment]
could name be a flag instead?

**Comment by dickeyxxx** [comment]
oh nevermind I see that's how things were before. I think it's better to have name as a flag, 2 arguments is already difficult for users to understand the order, adding a third just makes it even more confusing

**Comment by ransombriggs** [comment]
Leaving as a flag for now and closing.
